### ISSUE TITLE
Support more game

### ISSUE THREAD

**Issue by eprilx** [eprilx/FFDConverter#2]
**Just upload \*.ffd or \*.Fire_Font_Descriptor and font images/textures files (if you can get it) here then I will work on it.**

More games from Ubisoft that I haven't researched, if you have any info about fonts please let me know.
- Prince of Persia series
- Tom Clancy series
- South Park series
- The Crew 1, 2
- Call of Juarez: Bound in Blood
- I am alive
- ...

**Comment by rezamms** [comment]
far cry 4 font files:
https://www.mediafire.com/file/wl8ld8k6eiczz14/fire.zip/file

**Comment by eprilx** [comment]
> far cry 4 + Blood Dragon font files: https://www.mediafire.com/file/wl8ld8k6eiczz14/fire.zip/file

which one is FC4 and which one is Blood Dragon ?

**Comment by eprilx** [comment]
> ACB & ACR font

Supported in [v1.1.4](https://github.com/eprilx/FFDConverter/releases/tag/1.1.4)

**Comment by eprilx** [comment]
> I think it would be much better to add a list of supported games with the names of those who helped support that game. 😁

I will add the credit name directly to the tool in the next version.

**Comment by eprilx** [comment]
The font in FC2 *.mft is very different from ffd, it will take me more time to research and I still can't find the font in AC1.

**Comment by abodora** [comment]
> The font in FC2 *.mft is very different from ffd, it will take me more time to research and I still can't find the font in AC1.

That's right, Also FC1 font type is *.TTF

**Comment by rm-NoobInCoding** [comment]
Can you add this feature to your tool that can convert orginal ffd to xml?
I want to change farcry 5 fonts for Arabic, but I can not convert ffd to xml

**Comment by CloudBank-3055** [comment]
Dear author,
Thank you for your vital work! I am currently working on the Chinese translation of Anno 2205. I have tried to convert FFD using XML files from other games, but some of them work and some don't. Here are the FFD and DDS files of Anno 2205
[Anno 2205.zip](https://github.com/eprilx/FFDConverter/files/7601652/Anno.2205.zip)
.

**Comment by CloudBank-3055** [comment]
And here are the files from the existing Chinese translation package on the Internet, which are not clearly displayed in the game. Hopefully it will be of some help :)
[Anno 2205-Chinese translation.zip](https://github.com/eprilx/FFDConverter/files/7601700/Anno.2205-Chinese.translation.zip)

**Comment by eprilx** [comment]
@CloudBank-3055 supported Anno 2205 in [v1.3.2](https://github.com/eprilx/FFDConverter/releases/tag/1.3.2) (`-v Anno2205`)

**Comment by ARIAsTr** [comment]
Hello. Thanks for the good software.
But I have a problem. When I use this software to create fonts for far cry 3 game, the font game does not show properly. And it shows the font very messily. I did all the instructions you said but still my problem was not solved.
I will upload the photo of my problem here so that you can see it and you can help me.

![Problem](https://user-images.githubusercontent.com/98426159/155577012-afe8b398-294c-4389-9a89-4edc5b57594a.jpg)

**Comment by eprilx** [comment]
@ARIAsTr Hi, you can try increasing "scaleXadvance" and creating a distance field font.

**Comment by ARIAsTr** [comment]
> 

How I can Create a distance field font?

**Comment by eprilx** [comment]
> How I can Create a distance field font?

Note 2 in README.md

**Comment by PxpUii** [comment]
Can you make a Total war game font generator?
font in game : https://www.mediafire.com/file/dm1oklax6mbephq/font.rar/file

**Comment by eprilx** [comment]
> Can you make a Total war game font generator? font in game : https://www.mediafire.com/file/dm1oklax6mbephq/font.rar/file

Sorry, I'm not interested in these games.
There's an old tool (source code included) for these files https://www.twcenter.net/forums/showthread.php?357460-Release-of-the-CUF-(font-amp-text-rendering)-mod-tool

**Comment by Ezio-2005** [comment]
Hi, I used your software For Assassin's Creed, BrotherHood, but it does not show the font correctly. What is the reason?
![Error](https://user-images.githubusercontent.com/102662700/160822851-f81a8a0b-b4e3-4b37-a123-57aacdf18277.jpg)

**Comment by eprilx** [comment]
@Ezio-2005 maybe you didn't replace or replaced the wrong texture or .Fire_Font_Descriptor files.

**Comment by Ezio-2005** [comment]
> 

I replaced the fonts correctly.
But as for the texture you say, I did not find anything.
Do you know the names of these textures that you say? Because I searched, I did not find anything specific about the texture.

**Comment by eprilx** [comment]
@Ezio-2005 It usually in:
DataPC.forge
DataPC.forge/Game Bootstrap Settings
DataPC_extra.forge
*_patch.forge

It must have the same font name.
If your FFD is "2282-AC2Aaux_ProMedium_Latin.Fire_Font_Descriptor" then the texture is
"1446-AC2Aaux_ProMedium_Latin_1_MapDesc.data" or \*AC2Aaux*.*

If the extenstion is .data, use DATA tool to un(pack) it. Otherwise, it's just a "raw" texture that requires [Raw texture previewer](https://forum.xentax.com/viewtopic.php?f=18&t=16461&sid=66a6bfbcde9a4fe2f516ee777144dd79) to view, a hex editor to edit, a convert DDS tool (TexConv) to convert your DDS/PNG to (BC1, BC2, BC3, ...) same as the original texture.

**Comment by Ezio-2005** [comment]
> @Ezio-2005 It usually in: DataPC.forge DataPC.forge/Game Bootstrap Settings DataPC_extra.forge *_patch.forge
> 
> It must have the same font name. If your FFD is "2282-AC2Aaux_ProMedium_Latin.Fire_Font_Descriptor" then the texture is "1446-AC2Aaux_ProMedium_Latin_1_MapDesc.data" or *AC2Aaux*.*
> 
> If the extenstion is .data, use DATA tool to un(pack) it. Otherwise, it's just a "raw" texture that requires [Raw texture previewer](https://forum.xentax.com/viewtopic.php?f=18&t=16461&sid=66a6bfbcde9a4fe2f516ee777144dd79) to view, a hex editor to edit, a convert DDS tool (TexConv) to convert your DDS/PNG to (BC1, BC2, BC3, ...) same as the original texture.

thanks a lot
But for editing, I must know how to work with Hex Editor Or Not? Is there no other way to edit it?

**Comment by eprilx** [comment]
@Ezio-2005 You can view/export textures by using [Blacksmith](http://t-poses.com/bs/) or [ARchive_neXt](https://forum.xentax.com/viewtopic.php?f=10&t=6617) ... But as far as I know there's no tool to replace/import textures in these AC games except a hex editor.

**Comment by Ezio-2005** [comment]
Oh...Ok
Thanks Again My Friend.

**Comment by PxpUii** [comment]
How can we create a font like this?
https://www.mediafire.com/file/4nh7kzvyr6sbpjo/fonttexture.rar/file

**Comment by PxpUii** [comment]
How can we create a font like this?
https://www.mediafire.com/file/4nh7kzvyr6sbpjo/fonttexture.rar/file

**Comment by eprilx** [comment]
> How can i create a font like this? https://www.mediafire.com/file/4nh7kzvyr6sbpjo/fonttexture.rar/file

@PxpUii 
Bmfont to generate png and fnt.
Texconv to convert png to dds.
Make a tool to convert fnt to xml.
This topic is related to  **FFD**, please do not ask other things here.

**Comment by buhboyvjppro999** [comment]
hey, after i get the fnt file from your tool, what should i do next to be able to change the font in game? Can you help me?

**Comment by eprilx** [comment]
@buhboyvjppro999 If you used "FFD to FNT", you have to modify the fnt file with notepad and modify the texture with photoshop or sth.

**Comment by buhboyvjppro999** [comment]
Thank you. Everything is fine, but i am having trouble with "1-Abstergo_Sans_Latin_1_Map.-1565005545", i think it's the texture, do you know how to modify it ?

**Comment by eprilx** [comment]
@buhboyvjppro999 [As I said before](https://github.com/eprilx/FFDConverter/issues/2#issuecomment-1083449482), use a hex editor like hxd...

**Comment by Mstr-Samuel** [comment]
hi, i want to convert Fire_Font_Descriptor to .fnt, but it's comes with this error:
[Unhandled exception. System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Gibbed.IO.SmallWorkBuffer.ReadBytes(Stream stream, Int32 count) in D:\a\FFDConverter\FFDConverter\FFDConverter\Gibbed.IO\SmallWorkBuffer.cs:line 55
   at FFDConverter.FFDFormat.ReadTable1FFD(FileStream input, general& infoFFD) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFormat.cs:line 240
   at FFDConverter.FFDFormat.Load(String inputFFD, Config& config) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFormat.cs:line 42
   at FFDConverter.FFDFunction.ConvertFFDtoFNT(String inputFFD, String outputFNT, String versionGame) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFunction.cs:line 39
   at FFDConverter.Program.Main(String[] args) in D:\a\FFDConverter\FFDConverter\FFDConverter\Program.cs:line 151]
   what should i do? what is the problem?

**Comment by eprilx** [comment]
@Mstr-Samuel Please upload your sample file first.

**Comment by Mstr-Samuel** [comment]
> @Mstr-Samuel Please upload your sample file first.
[Sample 1](https://cdn.discordapp.com/attachments/998923003754729565/1149307339837542410/1711_-_AC2Aaux_ProLight_Latin.rar) , [Sample 2](https://cdn.discordapp.com/attachments/998923003754729565/1149307340185673868/1717_-_AC2Aaux_ProMedium_Latin.rar)

**Comment by eprilx** [comment]
@Mstr-Samuel 
We discuss this issue here: https://github.com/eprilx/FFDConverter/issues/6

**Comment by eprilx** [comment]
@Ezio-2005 @buhboyvjppro999 
There is a tool for modding image/texture font whithout using these hex, it's [AnvilToolkit](https://www.nexusmods.com/assassinscreedbrotherhood/mods/21) created by Kamzik123. Thanks to @Mstr-Samuel for pointing that out.

**Comment by Ezio-2005** [comment]
> @Ezio-2005 @buhboyvjppro999 @PxpUii There is a tool for modding image/texture font whithout using these hex, it's [AnvilToolkit](https://www.nexusmods.com/assassinscreedbrotherhood/mods/21) created by Kamzik123. Thanks to @Mstr-Samuel for pointing that out.


Thank's for this but I have use this tool and And I managed to change the texture of the font, but the problem is still there
That is, when I edit the texture, and when I make the FFD font with your software, and when I put it in the game, the font is still displayed in a mess.

**Comment by eprilx** [comment]
@Ezio-2005 
We disscuss this issue here: #7

**Comment by Johntaber0007** [comment]
Hello, can you add support for AC Shadows fonts? It's a bitmap font that has multiple images in one file.

[ACShadows_Fonts.zip](https://github.com/user-attachments/files/19395305/ACShadows_Fonts.zip)

**Comment by zerlkung** [comment]
Is there any chance it will work with ps4 swizzle? I tried converting the texture to ps4 and pack it back but the fonts don't show up.

**Comment by Gmk999** [comment]
[PrinceofPersia_ForgottenSands_FFD.zip](https://github.com/user-attachments/files/20620908/PrinceofPersia_ForgottenSands_FFD.zip)   Prince of Persia: Forgotten Sands FireFontDescriptor

**Comment by anlaarm** [comment]
Where is the FFD file in ACB? I know it's in DataPC.forge, but what file exactly?
