### ISSUE TITLE
AC2 error when convert Fire_Font_Descriptor to fnt

### ISSUE THREAD

**Issue by eprilx** [eprilx/FFDConverter#6]
hi, i want to convert Fire_Font_Descriptor to .fnt, but it's comes with this error:

[Unhandled exception. System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Gibbed.IO.SmallWorkBuffer.ReadBytes(Stream stream, Int32 count) in D:\a\FFDConverter\FFDConverter\FFDConverter\Gibbed.IO\SmallWorkBuffer.cs:line 55
   at FFDConverter.FFDFormat.ReadTable1FFD(FileStream input, general& infoFFD) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFormat.cs:line 240
   at FFDConverter.FFDFormat.Load(String inputFFD, Config& config) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFormat.cs:line 42
   at FFDConverter.FFDFunction.ConvertFFDtoFNT(String inputFFD, String outputFNT, String versionGame) in D:\a\FFDConverter\FFDConverter\FFDConverter\FFD\FFDFunction.cs:line 39
   at FFDConverter.Program.Main(String[] args) in D:\a\FFDConverter\FFDConverter\FFDConverter\Program.cs:line 151]
   
   what should i do? what is the problem?
   it's for AC2

_Originally posted by @Mstr-Samuel in https://github.com/eprilx/FFDConverter/issues/2#issuecomment-1708284790_

**Comment by eprilx** [comment]
Does that file come from ps, xbox or... ?
What tool do you use to get these files ?
I need more details because I see a slight difference in formatting between your version and the steam version.

**Comment by Mstr-Samuel** [comment]
> Does that file come from ps, xbox or... ? What tool do you use to get these files ? I need more details because I see a slight difference in formatting between your version and the steam version. Also, the name extension does not have any "_", it should be **Fire_Font_Descriptor**.

it's PC, the tool is AnvilToolKit. i don't know why it's different.

**Comment by eprilx** [comment]
It's because AnvilToolKit export wrong format. All my samples (include other games) is exported from Ubisoft_Data_Tool_by_Delluto.
You can workaround it by modifying unkHeader1 in config.xml file to **4** and replace the extension FireFontDescriptor ![image](https://github.com/eprilx/FFDConverter/assets/49425492/2f413b3f-11d3-4220-b0fb-0ec82103fb9d) 
or contact the AnvilToolKit author.

**Comment by Mstr-Samuel** [comment]
okay, thanks, this problem is solved.
